"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _dashboard_page from './dashboard-page.bones.json'
import _products_page from './products-page.bones.json'

registerBones({
  "dashboard-page": _dashboard_page,
  "products-page": _products_page,
})
